name: Lint CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install cpplint
      run: pip install cpplint
    - name: run linter
      run: make lint
